name: macOS Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Test build on ${{ matrix.os }} with Qt ${{ matrix.qt_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macOS-latest']
        qt_version: ['5.12.6']

    steps:
    - name: Install Qt ${{ matrix.qt_version }}
      uses: jurplel/install-qt-action@v2.2.1
      with:
        version: ${{ matrix.qt_version }}
        target: desktop

    - name: Checkout
      uses: actions/checkout@v1

    - name: Update git submodules
      run: |
        git submodule update --init --recursive

    - name: Configure & Build
      run: |
        mkdir build
        cd build/
        cmake -DCMAKE_PREFIX_PATH="${Qt5_Dir}" -DCMAKE_BUILD_TYPE=Release ../
        make -j

    - name: Run Tests
      run: |
        sh scripts/run_tests.sh build
