name: Ubuntu Build-Test

on:
  push:
    branches:
      - fix-build-errors
      - git-workflow
         
jobs:
  build:
    name: Test build on ${{ matrix.os }} with Qt ${{ matrix.qt_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        qt_version: ['5.12.6']
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install Qt ${{ matrix.qt_version }}
      uses: jurplel/install-qt-action@v2.2.1
      with:
        version: ${{ matrix.qt_version }}
        target: desktop

    - name: Install dependencies
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz
        tar xvfz cmake-3.16.2-Linux-x86_64.tar.gz
        export PATH="${PWD}/cmake-3.16.2-Linux-x86_64/bin:$PATH"
        cmake --version

    - name: Configure build
      run: |
        mkdir build
        cd build/
        cmake --version
        echo ${Qt5_Dir}
        cmake -DCMAKE_PREFIX_PATH=${Qt5_Dir} -DCMAKE_BUILD_TYPE=Release ../
    #     #./configure
    
    #- name: Build
    #  run: make
