name: Ubuntu Build Test

on:
  push:
    branches:
      - fix-build-errors
      - git-workflow
         
jobs:
  build:
    name: Test build on ${{ matrix.os }} with Qt ${{ matrix.qt_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        qt_version: ['5.12.6']
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install Qt ${{ matrix.qt_version }}
      uses: jurplel/install-qt-action@v2.2.1
      with:
        version: ${{ matrix.qt_version }} # version of Qt to install
        target: desktop # target platform for build
    
    - name: Install dependencies
      run: |
        apt-get install cmake libgl1-mesa-dev build-essential
    
    - name: Configure build
      run: |
        mkdir build
        cd build/
        cmake -DCMAKE_PREFIX_PATH=/Qt/${{ matrix.qt_version }}/gcc_64 -DCMAKE_BUILD_TYPE=Release ../
        #./configure
    
    - name: Build
      run: make
