name: Ubuntu Build

on: [pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Qt ${{ matrix.qt_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04']
        qt_version: ['5.12.6', '5.12.9', '5.15.2']

    steps:
    - name: Install Python 3.7 version
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install Qt ${{ matrix.qt_version }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        target: desktop

    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libpulse-dev libgl1-mesa-dev

    - name: Checkout
      uses: actions/checkout@v2

    - name: Update git submodules
      run: |
        git submodule update --init --recursive

    - name: Download CMake 3.16.2
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz
        tar xvfz cmake-3.16.2-Linux-x86_64.tar.gz

    - name: Configure & Build
      run: |
        mkdir build
        cd build/
        ../cmake-3.16.2-Linux-x86_64/bin/cmake -DCMAKE_PREFIX_PATH=${Qt5_Dir} -DCMAKE_BUILD_TYPE=Release ../
        make -j

    - name: Unit Tests
      run: |
        sh scripts/run_tests.sh build

    - name: Test Deploy Script
      run: |
        cd build/
        mv gui/dancebotsEditor dancebots-editor
        tar -zcvf dancebots-editor-ubuntu.tar.gz dancebots-editor

    # - name: Upload Release Asset
    #   id: upload-release-asset
    #   if: startsWith(github.ref, 'refs/tags/')
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets{?name,label}"
    #     asset_path: build/dancebots-editor-ubuntu.tar.gz
    #     asset_name: dancebots-editor-ubuntu.tar.gz
    #     asset_content_type: application/zip

