name: Ubuntu Build-Test

on:
  push:
    branches:
      - fix-build-errors
      - git-workflow
         
jobs:
  build:
    name: Test build on ${{ matrix.os }} with Qt ${{ matrix.qt_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        qt_version: ['5.12.6']
    
    steps:
    - uses: actions/checkout@v1
    
    # - name: Install Qt ${{ matrix.qt_version }}
    #   uses: jurplel/install-qt-action@v2.2.1
    #   with:
    #     version: ${{ matrix.qt_version }} # version of Qt to install
    #     target: desktop # target platform for build

    - name: Install dependencies
      run: |
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
        sudo apt-get update
        sudo apt-get install cmake
        cmake --version
#        wget https://cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.tar.gz
#        tar xf cmake-3.4.1-Linux-x86_64.tar.gz
#        export PATH="`pwd`/cmake-3.4.1-Linux-x86_64/bin:$PATH" # save it in .bashrc if needed

    # - name: Configure build
    #   run: |
    #     mkdir build
    #     cd build/
    #     cmake --version
    #     echo ${Qt5_Dir}
    #     #cmake -DCMAKE_PREFIX_PATH=${Qt5_Dir} -DCMAKE_BUILD_TYPE=Release ../
    #     #./configure
    
    #- name: Build
    #  run: make
